set(CPACK_PACKAGE_VENDOR "Prusa3D")
set(CPACK_PACKAGE_CONTACT "Contact Name <contact@prusa3d.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Slic3r is a slicer for 3D printers")
#set(CPACK_PACKAGE_VERSION_MAJOR 1)
#set(CPACK_PACKAGE_VERSION_MINOR 1)
#set(CPACK_PACKAGE_VERSION_PATCH 1)
if(NOT DEFINED CPACK_PACKAGE_VERSION)
	set(CPACK_PACKAGE_VERSION "1.33.8")
endif()
set(CPACK_GENERATOR "DEB")
if(NOT DEFINED CPACK_DEBIAN_PACKAGE_ARCHITECTURE)
	execute_process(COMMAND dpkg --print-architecture OUTPUT_VARIABLE CPACK_DEBIAN_PACKAGE_ARCHITECTURE OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()
set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")

set(DEB_DEPENDS
	"perl (>= 5.20.2)"
	"libextutils-typemaps-default-perl (>= 1.05)"
	"libextutils-xspp-perl (>= 0.1800)"
)

string(REPLACE ";" "," DEB_DEPENDS "${DEB_DEPENDS}")
set(CPACK_DEBIAN_PACKAGE_DEPENDS ${DEB_DEPENDS})

include(CPack)
